title: Affan Iman Azman
logo: assets/img/linkedin_dronelab.jpeg
description: Robotics Research Assistant at Universiti Sains Malaysia | Engineering Design Space Lab
show_downloads: true
# Theme Configuration
theme: jekyll-theme-minimal
